In [286]:
import pandas as pd

In [287]:
data = pd.read_excel('./Customer Call List (1).xlsx')
print(f'dataset loaded with {data.shape[0]} rows and {data.shape[1]} columns')

dataset loaded with 21 rows and 8 columns

In [288]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     str
 2   Last_Name          20 non-null     str
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     str
 5   Paying Customer    21 non-null     str
 6   Do_Not_Contact     17 non-null     str
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(1), str(5)
memory usage: 1.3+ KB

In [289]:
data.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

# 1. Drop Duplicates

In [290]:
# find duplicates
data[data.duplicated(keep=False)]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [291]:
# drop duplicates
data = data.drop_duplicates()

In [292]:
data[data.duplicated(keep=False)]

Empty DataFrame
Columns: [CustomerID, First_Name, Last_Name, Phone_Number, Address, Paying Customer, Do_Not_Contact, Not_Useful_Column]
Index: []

# 2. Delete Not useful columns

In [293]:
data.columns.to_list()

['CustomerID',
 'First_Name',
 'Last_Name',
 'Phone_Number',
 'Address',
 'Paying Customer',
 'Do_Not_Contact',
 'Not_Useful_Column']

In [294]:
data.drop('Not_Useful_Column', axis=1, inplace=True)

In [295]:
data.columns.to_list()

['CustomerID',
 'First_Name',
 'Last_Name',
 'Phone_Number',
 'Address',
 'Paying Customer',
 'Do_Not_Contact']

# 3. Clean last names

In [296]:
data['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: str

In [297]:
data['Last_Name'] = data['Last_Name'].str.replace(r'^[^a-zA-Z]+|[^a-zA-Z]+$', '', regex=True)

# 4. reFormatting phone numbers

In [298]:
data['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [299]:
data['Phone_Number'] = data['Phone_Number'].astype('str').str.replace(r'[^0-9]', '', regex=True)
data['Phone_Number']

0     1235455421
1     1236439775
2     7066950392
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8
9     1235455421
10           NaN
11    7066950392
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17    7066950392
18
19    8766783469
Name: Phone_Number, dtype: str

In [300]:
data['Phone_Number'] = data['Phone_Number'].replace('nan', pd.NA)

In [301]:
def format_phone(phone):
    if pd.isna(phone) or phone == '':
        return pd.NA
    if len(phone) == 10:
        return f'{phone[:3]}-{phone[3:6]}-{phone[6:]}'
    return phone


data['Phone_Number'] = data['Phone_Number'].apply(format_phone)

In [302]:
data['Phone_Number']

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6              NaN
7     876-678-3469
8              NaN
9     123-545-5421
10             NaN
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18             NaN
19    876-678-3469
Name: Phone_Number, dtype: str

# 5. reFormatting Address

In [303]:
data['Address']

0                     123 Shire Lane, Shire
1                       93 West Main Street
2                        298 Drugs Driveway
3     980 Paper Avenue, Pennsylvania, 18503
4                          123 Dragons Road
5                          768 City Parkway
6                         1209 South Street
7                             98 Clue Drive
8                          123 Middle Earth
9                25th Main Street, New York
10                    612 Shire Lane, Shire
11                     2394 Hogwarts Avenue
12                         2039 Main Street
13                         343 City Parkway
14                            214 HR Avenue
15                     2395 Hogwarts Avenue
16           121 Paper Avenue, Pennsylvania
17                          3498 Super Lane
18                                      N/a
19              910 Tatooine Road, Tatooine
Name: Address, dtype: str

In [304]:
data['Address'].str.split(',', n=2, expand=True)

                       0              1       2
0         123 Shire Lane          Shire     NaN
1    93 West Main Street            NaN     NaN
2     298 Drugs Driveway            NaN     NaN
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road            NaN     NaN
5       768 City Parkway            NaN     NaN
6      1209 South Street            NaN     NaN
7          98 Clue Drive            NaN     NaN
8       123 Middle Earth            NaN     NaN
9       25th Main Street       New York     NaN
10        612 Shire Lane          Shire     NaN
11  2394 Hogwarts Avenue            NaN     NaN
12      2039 Main Street            NaN     NaN
13      343 City Parkway            NaN     NaN
14         214 HR Avenue            NaN     NaN
15  2395 Hogwarts Avenue            NaN     NaN
16      121 Paper Avenue   Pennsylvania     NaN
17       3498 Super Lane            NaN     NaN
18                   N/a            NaN     NaN
19     910 Tatooine Road       Tatooine     NaN

In [305]:
data[['Street_Address', 'State', 'Zip_Code']] = data['Address'].str.split(',', n=2, expand=True)

# 6. masking Boolean Columns

In [306]:
data[['Paying Customer', 'Do_Not_Contact']]

   Paying Customer Do_Not_Contact
0              Yes             No
1               No            Yes
2                N            NaN
3              Yes              Y
4                Y             No
5              Yes            Yes
6               No             No
7                N             No
8              Yes            NaN
9              Yes             No
10             Yes             No
11               Y            NaN
12             Yes              N
13             Yes             No
14               N             No
15              No              N
16             Yes             No
17               Y            NaN
18             N/a            Yes
19             Yes              N

In [307]:
mask = {
    'Yes': True,
    'Y': True,
    'No': False,
    'N': False
}
data['Paying Customer'] = data['Paying Customer'].map(mask)
data['Do_Not_Contact'] = data['Do_Not_Contact'].map(mask)

In [308]:
data[['Paying Customer', 'Do_Not_Contact']]

   Paying Customer Do_Not_Contact
0             True          False
1            False           True
2            False            NaN
3             True           True
4             True          False
5             True           True
6            False          False
7            False          False
8             True            NaN
9             True          False
10            True          False
11            True            NaN
12            True          False
13            True          False
14           False          False
15           False          False
16            True          False
17            True            NaN
18             NaN           True
19            True          False

# 7. handling N/A and NAN values

In [309]:
data = data.fillna('')

In [310]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",True,False,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,False,True,93 West Main Street,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,False,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",True,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,True,False,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,True,True,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,False,False,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,False,False,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,True,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",True,False,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",True,False,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,True,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,True,False,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,True,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,False,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,False,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",True,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,True,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,,True,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",True,False,910 Tatooine Road,Tatooine,

# 8. handling if someone doesnt want to call

In [312]:
# for x in data.index:
#     if data.loc[x, 'Do_Not_Contact'] == True:
#         data.drop(x, inplace=True)
#     if data.loc[x, 'Do_Not_Contact'] == '':
#         data.drop(x, inplace=True)
#     if data.loc[x, 'Phone_Number'] == '':
#         data.drop(x, inplace=True)

data = data[~((data['Do_Not_Contact'] == True) | (data['Do_Not_Contact'] == '') | (data['Phone_Number'] == ''))]

In [314]:
data.reset_index(drop=True, inplace=True)

In [315]:
data

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",True,False,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,True,False,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,False,False,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",True,False,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,2039 Main Street,True,False,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,True,False,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,False,False,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,False,False,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",True,False,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",True,False,910 Tatooine Road,Tatooine,

In [324]:
data.to_csv('Cleaned_Customer_Call_List.csv', index=False)