In [48]:
import pandas as pd

In [49]:
data = pd.read_csv("hotel_bookings.csv", encoding="UTF-8")
print(f"dataset loaded with {data.shape[0]} rows and {data.shape[1]} columns")

dataset loaded with 119390 rows and 32 columns

In [50]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

In [51]:
data.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

# 1. rename or drop columns

In [52]:
data.columns.tolist()

['hotel',
 'is_canceled',
 'lead_time',
 'arrival_date_year',
 'arrival_date_month',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'adults',
 'children',
 'babies',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'reserved_room_type',
 'assigned_room_type',
 'booking_changes',
 'deposit_type',
 'agent',
 'company',
 'days_in_waiting_list',
 'customer_type',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'reservation_status',
 'reservation_status_date']

In [53]:
data.rename(
    {
        "adults": "number_of_adults",
        "children": "number_of_children",
        "babies": "number_of_babies",
    },
    axis=1,
    inplace=True,
)

In [54]:
data.columns.tolist()

['hotel',
 'is_canceled',
 'lead_time',
 'arrival_date_year',
 'arrival_date_month',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'number_of_adults',
 'number_of_children',
 'number_of_babies',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'reserved_room_type',
 'assigned_room_type',
 'booking_changes',
 'deposit_type',
 'agent',
 'company',
 'days_in_waiting_list',
 'customer_type',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'reservation_status',
 'reservation_status_date']

# 2. Handling NaN values

In [55]:
# Check the Percentage of Missing Data in Each Column
data.isna().sum() * 100 / len(data)

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
number_of_adults                   0.000000
number_of_children                 0.003350
number_of_babies                   0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [56]:
data.drop("company", axis=1, inplace=True)

In [57]:
data["agent"] = data["agent"].fillna(-1)

In [58]:
data["country"] = data["country"].fillna("unknown")

In [59]:
data.dropna(subset="number_of_children", inplace=True)

In [60]:
data.isna().sum() * 100 / len(data)

hotel                             0.0
is_canceled                       0.0
lead_time                         0.0
arrival_date_year                 0.0
arrival_date_month                0.0
arrival_date_week_number          0.0
arrival_date_day_of_month         0.0
stays_in_weekend_nights           0.0
stays_in_week_nights              0.0
number_of_adults                  0.0
number_of_children                0.0
number_of_babies                  0.0
meal                              0.0
country                           0.0
market_segment                    0.0
distribution_channel              0.0
is_repeated_guest                 0.0
previous_cancellations            0.0
previous_bookings_not_canceled    0.0
reserved_room_type                0.0
assigned_room_type                0.0
booking_changes                   0.0
deposit_type                      0.0
agent                             0.0
days_in_waiting_list              0.0
customer_type                     0.0
adr                               0.0
required_car_parking_spaces       0.0
total_of_special_requests         0.0
reservation_status                0.0
reservation_status_date           0.0
dtype: float64

# 3. data type Checks

In [61]:
data.info()

<class 'pandas.DataFrame'>
Index: 119386 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119386 non-null  str
 1   is_canceled                     119386 non-null  int64
 2   lead_time                       119386 non-null  int64
 3   arrival_date_year               119386 non-null  int64
 4   arrival_date_month              119386 non-null  str
 5   arrival_date_week_number        119386 non-null  int64
 6   arrival_date_day_of_month       119386 non-null  int64
 7   stays_in_weekend_nights         119386 non-null  int64
 8   stays_in_week_nights            119386 non-null  int64
 9   number_of_adults                119386 non-null  int64
 10  number_of_children              119386 non-null  float64
 11  number_of_babies                119386 non-null  int64
 12  meal                            119386 non-null  str
 13  country                         119386 non-null  str
 14  market_segment                  119386 non-null  str
 15  distribution_channel            119386 non-null  str
 16  is_repeated_guest               119386 non-null  int64
 17  previous_cancellations          119386 non-null  int64
 18  previous_bookings_not_canceled  119386 non-null  int64
 19  reserved_room_type              119386 non-null  str
 20  assigned_room_type              119386 non-null  str
 21  booking_changes                 119386 non-null  int64
 22  deposit_type                    119386 non-null  str
 23  agent                           119386 non-null  float64
 24  days_in_waiting_list            119386 non-null  int64
 25  customer_type                   119386 non-null  str
 26  adr                             119386 non-null  float64
 27  required_car_parking_spaces     119386 non-null  int64
 28  total_of_special_requests       119386 non-null  int64
 29  reservation_status              119386 non-null  str
 30  reservation_status_date         119386 non-null  str
dtypes: float64(3), int64(16), str(12)
memory usage: 29.1 MB

In [71]:
data["number_of_children"] = data["number_of_children"].astype("int")
data["agent"] = data["agent"].astype("int")

data = data.astype({"is_canceled": "boolean", "is_repeated_guest": "boolean"})

In [72]:
data.info()

<class 'pandas.DataFrame'>
Index: 119386 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119386 non-null  str
 1   is_canceled                     119386 non-null  boolean
 2   lead_time                       119386 non-null  int64
 3   arrival_date_year               119386 non-null  int64
 4   arrival_date_month              119386 non-null  str
 5   arrival_date_week_number        119386 non-null  int64
 6   arrival_date_day_of_month       119386 non-null  int64
 7   stays_in_weekend_nights         119386 non-null  int64
 8   stays_in_week_nights            119386 non-null  int64
 9   number_of_adults                119386 non-null  int64
 10  number_of_children              119386 non-null  int64
 11  number_of_babies                119386 non-null  int64
 12  meal                            119386 non-null  str
 13  country                         119386 non-null  str
 14  market_segment                  119386 non-null  str
 15  distribution_channel            119386 non-null  str
 16  is_repeated_guest               119386 non-null  boolean
 17  previous_cancellations          119386 non-null  int64
 18  previous_bookings_not_canceled  119386 non-null  int64
 19  reserved_room_type              119386 non-null  str
 20  assigned_room_type              119386 non-null  str
 21  booking_changes                 119386 non-null  int64
 22  deposit_type                    119386 non-null  str
 23  agent                           119386 non-null  int64
 24  days_in_waiting_list            119386 non-null  int64
 25  customer_type                   119386 non-null  str
 26  adr                             119386 non-null  float64
 27  required_car_parking_spaces     119386 non-null  int64
 28  total_of_special_requests       119386 non-null  int64
 29  reservation_status              119386 non-null  str
 30  reservation_status_date         119386 non-null  str
dtypes: boolean(2), float64(1), int64(16), str(12)
memory usage: 27.8 MB

In [73]:
data.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,number_of_adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,False,342,2015,July,27,1,0,0,2,...,3,No Deposit,-1,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,False,737,2015,July,27,1,0,0,2,...,4,No Deposit,-1,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,False,7,2015,July,27,1,0,1,1,...,0,No Deposit,-1,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,False,13,2015,July,27,1,0,1,1,...,0,No Deposit,304,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,False,14,2015,July,27,1,0,2,2,...,0,No Deposit,240,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,False,14,2015,July,27,1,0,2,2,...,0,No Deposit,240,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,False,0,2015,July,27,1,0,2,2,...,0,No Deposit,-1,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,False,9,2015,July,27,1,0,2,2,...,0,No Deposit,303,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,True,85,2015,July,27,1,0,3,2,...,0,No Deposit,240,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,True,75,2015,July,27,1,0,3,2,...,0,No Deposit,15,0,Transient,105.5,0,0,Canceled,2015-04-22